on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Polyfill AWS certificates
      run: |
        cd components/ClientComponent/
        touch ca.crt client.crt client.key aws.url
    - name: Build ESP-IDF project
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3.1
        target: esp32
